Repository LeaseLens/LeaseLens_BackEnd, pull requests merged in 2024-06, with the labels that each got.

#2 Test 폴더 병합
  Test/app.js
Labels: 🛠️ refactor

#28 Docs: Readme.md 파일에 폴더 구조 업데이트
  README.md
Labels: 📜docs

#30 Refactor : 향후 작업을 위한 기본 폴더구조 및 파일 작성
  backend/Middlewares/middlewares.js
  backend/app.js
  backend/controller/loginController.js
  backend/controller/productController.js
  backend/controller/renderController.js
  backend/controller/reviewController.js
  backend/controller/userController.js
  backend/routes/adminRouter.js
  backend/routes/index.js
  backend/routes/loginRouter.js
  backend/routes/productRouter.js
  backend/routes/renderRouter.js
  backend/routes/reviewRouter.js
  backend/routes/userRouter.js
Labels: 🛠️ refactor

#32 FEAT:에러 처리 미들웨어 추가가
  backend/app.js
Labels: 🔥feat, 🛠️ refactor

#36 FIX : 데이터베이스 연결 오류 해결
  backend/controller/productController.js
Labels: 🐞 fix

#37 FEAT : 제품 상세 페이지 렌더링 구현
  backend/controller/productController.js
  backend/routes/productRouter.js
Labels: 🔥feat

#38 FEAT : 찜하기 기능 구현
  backend/controller/productController.js
Labels: 🔥feat

#39 FEAT : 리뷰게시판 조회 및 검색 구현
  backend/controller/productController.js
  backend/controller/reviewController.js
  backend/routes/reviewRouter.js
Labels: 🔥feat

#40 FEAT : 리뷰 작성하기 버튼 구현
  backend/controller/reviewController.js
Labels: 🔥feat

#41 FEAT : 리뷰 삭제하기 기능 구현
  backend/controller/reviewController.js
Labels: 🔥feat

#42 FEAT : 댓글 작성 기능 구현
  backend/controller/reviewController.js
  backend/routes/reviewRouter.js
Labels: 🐞 fix, 🔥feat

#44 FEAT: User 인증 관련 기능
  Test/ImageBlobTest/App.js
  Test/ImageBlobTest/client/.gitignore
  Test/ImageBlobTest/client/README.md
  Test/ImageBlobTest/client/package-lock.json
  Test/ImageBlobTest/client/package.json
  Test/ImageBlobTest/client/public/favicon.ico
  Test/ImageBlobTest/client/public/index.html
  Test/ImageBlobTest/client/public/logo192.png
  Test/ImageBlobTest/client/public/logo512.png
  Test/ImageBlobTest/client/public/manifest.json
  Test/ImageBlobTest/client/public/robots.txt
  Test/ImageBlobTest/client/src/App.css
  Test/ImageBlobTest/client/src/App.js
  Test/ImageBlobTest/client/src/App.test.js
  Test/ImageBlobTest/client/src/index.css
  Test/ImageBlobTest/client/src/index.js
  Test/ImageBlobTest/client/src/logo.svg
  Test/ImageBlobTest/client/src/reportWebVitals.js
  Test/ImageBlobTest/client/src/setupTests.js
  Test/ImageBlobTest/example_image.png
  Test/ImageBlobTest/package-lock.json
  Test/ImageBlobTest/package.json
  Test/ImageBlobTest/server/App.js
  Test/ImageBlobTest/server/example_image.png
  Test/ImageBlobTest/testblob.js
  Test/sessionTest/app.js
  Test/sessionTest/jwtTest.js
  Test/sessionTest/package-lock.json
  Test/sessionTest/package.json
  Test/sessionTest/views/hello.ejs
  backend/Middlewares/handleError.js
  backend/Middlewares/isLoggedIn.js
  backend/Middlewares/isNotLoggedIn.js
  backend/app.js
  backend/config/config.js
  backend/controller/userController.js
  backend/models/index.js
  backend/models/user.js
  backend/package.json
  backend/passport/index.js
  backend/passport/local.js
  backend/routes/userRouter.js
Labels: 🔥feat, 🧪test

#46 TEST : 데이터 입력하기
  backend/app.js
  backend/config/config.js
  backend/models/product.js
  backend/seeders/insertProducts.js
Labels: 🔥feat, 🛠️ refactor

#47 REFACTOR : 이미지 업로드 + 삭제 구현
  backend/Middlewares/isLoggedIn.js
  backend/Middlewares/isNotLoggedIn.js
  backend/controller/reviewController.js
  backend/routes/productRouter.js
  backend/routes/renderRouter.js
  backend/routes/reviewRouter.js
Labels: 🔥feat, 🛠️ refactor

#48 FEAT : 리뷰 상세보기 페이지 구현
  backend/controller/reviewController.js
  backend/seeders/insertProducts.js
Labels: 🔥feat, 🛠️ refactor

#49 FEAT : 리뷰 댓글 수정 기능 구현
  backend/controller/reviewController.js
Labels: 🔥feat

#50 FEAT : 댓글 삭제하기 기능 구현
  backend/controller/reviewController.js
Labels: 🐞 fix, 🔥feat

#51 FEAT : 메인페이지 렌더링 구현
  backend/controller/renderController.js
Labels: 🔥feat

#53 FIX : 데이터 중복입력 에러 해결
  backend/seeders/insertProducts.js
Labels: 🐞 fix

#54 FEAT : 마이페이지 렌더링 구현
  backend/controller/renderController.js
  backend/models/favorite.js
  backend/models/index.js
Labels: 🐞 fix, 🔥feat, 🛠️ refactor

#57 FIX : Issue/55 main에 병합
  backend/Middlewares/isAdmin.js
  backend/Middlewares/isLoggedIn.js
  backend/Middlewares/isNotLoggedIn.js
  backend/app.js
  backend/config/adminSetup.js
  backend/controller/adminReviewController.js
  backend/controller/productController.js
  backend/controller/renderController.js
  backend/controller/reviewController.js
  backend/controller/userController.js
  backend/models/index.js
  backend/models/review.js
  backend/models/user.js
  backend/package.json
  backend/passport/index.js
  backend/passport/local.js
  backend/routes/adminReviewRouter.js
  backend/routes/index.js
Labels: 🐞 fix

#60 FIX : 모든 라우터 연결 구현 완료
  backend/controller/reviewController.js
Labels: 🐞 fix, 🛠️ refactor

#67 REFACTOR : idx로 전송형식 고정
  backend/controller/adminReviewController.js
  backend/controller/productController.js
  backend/controller/renderController.js
  backend/controller/reviewController.js
  backend/models/comment.js
  backend/models/favorite.js
  backend/models/product.js
  backend/models/review.js
  backend/models/user.js
  backend/passport/index.js
Labels: 🛠️ refactor

#69 FIX : 비로그인 상태 에러메시지 출력
  backend/controller/reviewController.js
Labels: 🐞 fix

#70 FIX : product text 전송 안됨
  backend/controller/productController.js
  backend/controller/renderController.js
Labels: 🐞 fix

#74 FEAT : 제품 찜하기 여부 전송
  backend/controller/productController.js
Labels: 🔥feat

#75 FEAT : prod_likes 좋아요 개수 계산하기
  backend/controller/productController.js
  backend/seeders/insertProducts.js
Labels: 🔥feat

#76 FEAT : 로그인, 비로그인 상태를 판별하는 라우터 경로 추가
  backend/controller/renderController.js
  backend/routes/renderRouter.js
Labels: 🔥feat

#81 REFACTOR : issue/6 브랜치 병합
  backend/app.js
  backend/config/adminSetup.js
  backend/controller/renderController.js
  backend/controller/reviewController.js
  backend/package.json
  backend/routes/index.js
  backend/routes/renderRouter.js
  backend/routes/reviewRouter.js
Labels: 🛠️ refactor

#87 FEAT : 회원 탈퇴 시 연결된 모든 정보 삭제
  .gitignore
  backend/controller/userController.js
Labels: 🔥feat
